### ISSUE TITLE
Have you gone through a paper on GAME Net?

### ISSUE THREAD

**Issue by WrathofBhuvan11** [mp2893/mime#2]
https://github.com/sjy1203/GAMENet

**Comment by mp2893** [comment]
Sure I know the paper. Two of the authors are also on MiME.

**Comment by WrathofBhuvan11** [comment]
Bro , I'm a undergraduate student and hobbyist. I'm currently working on
medical annotations, drug discovery and stuff. I'm following all of your
work.
When can I expect you to upload MiME work in Ur repository. I'm ultimately
trying to develop my own architecture.
