### ISSUE TITLE
Instructions Needed

### ISSUE THREAD

**Issue by virajbhalala** [mp2893/mime#5]
I read your paper, its a great effort in Multi-level Medical Embedding. Can I know when detailed instructions will be added in readme file? Currently it is quite difficult to understand just the code. Instruction similar to ones that is in your Retain and med2vec and DoctorAI that shows how to prepare input data and train model will help users to use this work. Thanks!

**Comment by mp2893** [comment]
Hi Viraj,

I know it has been long overdue, but I just updated the README to be a bit more informative. I also uploaded a sample dataset. Hope this helps.

Best,
Ed
