### ISSUE TITLE
mime in tensorflow 2.0

### ISSUE THREAD

**Issue by rafiuddinkhan** [mp2893/mime#7]
Hi, I found your paper quite interesting and have a great scope in medical prediction.
Can you please share code in TensorFlow 2.0 for ease in understanding.

**Comment by mp2893** [comment]
Hi Rafiuddin,

Thanks for taking interest in our work. I actually have not yet familiarized myself to TF 2.0. 
However, after releasing the GCT code, I'll try to change the MiME code to use Keras framework.

Best,
Ed
