### ISSUE TITLE
Extracting the dx or rx embeddings

### ISSUE THREAD

**Issue by akshatshreemali** [mp2893/mime#9]
This is not an issue but i have a question about extracting the dx embeddings from the model.
I created a model till the dx embedding layers.
Now, while creating the pickle files for the input, I have a dictionary which maps each diagnosis code with its respective integer(starting from 1 till the max number).

Now, in the embedding layer, can i directly extract the weights and map the index to the diagnosis code index? I noticed that the input is not shuffled with respect to the diagnosis codes but at patient level only.

Please tell me if there is a better way to do that.

**Comment by mp2893** [comment]
Hi Akshat,

Yes you can certainly do that. At the time of writing MiME code, I was not taking advantage of the lookup functions, so if you are able to implement that, you should certainly try it.

Best,
Ed

**Comment by akshatshreemali** [comment]
Thanks for your reply :)
Really appreciate it.
Just a question regarding the training part. 
For multiple GPU, does the code needs to be modified or it will run on multiple GPU's without any configuration.

I noticed that you ran the code across 12GPU's. 
It would be great if you can share some details.

**Comment by mp2893** [comment]
I don't remember training MiME using multiple GPUs (not data-parallel, nor model-parallel).
The MiME code was written quite some time ago, so I can't really guarantee that it would train on multiple GPUs without any hiccups.

**Comment by akshatshreemali** [comment]
okk. Thanks for your reply.
